use crate::formula::{
    AtomicWordEquation, ConjunctiveFormula, DisjunctiveFormula, EquationContent,
    ExistentialFormula, Formula, NegativeFormula, UniversalFormula,
};
use pest::iterators::{Pair, Pairs};
use pest::Parser;
use pest_derive::Parser;

/// The parser generated by [`pest`], implemented by the macro, using the grammar defined in
/// the file `formula.pest`
#[derive(Parser)]
#[grammar = "formula.pest"]
struct FormulaParser;

/// Tests that the generated parser [`FormulaParser`] doesn't fail on basic correct formulas
#[test]
fn test_parser() {
    let test_cases = [
        r#"x = "a" yqqq z"#,
        r#"¬x = "a" yqqq z"#,
        r#"(x=y"abc" && ¬y="m")"#,
    ];
    for case in test_cases {
        let rules = FormulaParser::parse(Rule::formula, case)
            .expect("should parse")
            .next()
            .unwrap();
        println!("Success {}", case);
        println!("{:#?}", rules);
    }
}

/// Creates a [`Formula`] object-based structural representation of the given formula string
pub fn parse_formula_str(eq: &str) -> Option<Box<dyn Formula + '_>> {
    let res = FormulaParser::parse(Rule::formula, eq);
    if let Ok(mut formula) = res {
        let formula = formula.next().unwrap();
        let formula = formula.into_inner().next().unwrap();
        let formula = parse_formula_pair(formula);
        Some(formula)
    } else {
        let error = res.unwrap_err();
        eprintln!("Syntax error in formula: {}", error);
        None
    }
}

/// Tests that the function [`parse_formula_str`] doesn't fail on some simple correct formulas
#[cfg(test)]
#[test]
fn test_formula_parse() {
    let test_cases = [
        r#"x = "a" yqqq z"#,
        r#"¬q = "a""#,
        r#"¬x = "a" yqqq z"#,
        r#"(x=y"abc" && ¬y="")"#,
        r#"exists x (U=x x)"#,
        r#"¬(x="aa"||x="bb")"#,
    ];
    for case in test_cases {
        let eq = parse_formula_str(case);
        match eq {
            None => {
                panic!("Parse error on formula\n{:?}", eq)
            }
            Some(val) => {
                println!("Success {}\n---------------", val);
            }
        }
    }
}

/// Parses a [`Pairs<Rule>`] sequence into an instance of [`AtomicWordEquation`]
fn parse_atomic_equation<'a>(eq: &mut Pairs<'a, Rule>) -> AtomicWordEquation<'a> {
    let lhs_var = eq.next().unwrap().as_str();
    let rhs = eq
        .map(|x| match x.as_rule() {
            Rule::constant => {
                let str = x.as_str();
                // remove " at start and end
                EquationContent::Constant(str[1..str.len() - 1].into())
            }
            Rule::variable => EquationContent::Variable(x.as_str()),
            _ => panic!("Unreachable state"),
        })
        .collect();

    AtomicWordEquation::new(lhs_var, rhs)
}

/// Parses a [`Pairs<Rule>`] sequence into an instance of [`NegativeFormula`]
fn parse_negation<'a>(eq: &mut Pairs<'a, Rule>) -> NegativeFormula<'a> {
    let inner = eq.next().unwrap().into_inner().next().unwrap();
    let atomic_eq = parse_formula_pair(inner);
    NegativeFormula::new(atomic_eq)
}

/// Parses a [`Pairs<Rule>`] sequence into an instance of [`ConjunctiveFormula`]
fn parse_conjunction<'a>(eq: &mut Pairs<'a, Rule>) -> ConjunctiveFormula<'a> {
    // for lhs and rhs, get the inner type within the formula rule
    let lhs_eq = eq.next().unwrap();
    let lhs_eq = lhs_eq.into_inner().next().unwrap();

    let rhs_eq = eq.next().unwrap();
    let rhs_eq = rhs_eq.into_inner().next().unwrap();

    let lhs = parse_formula_pair(lhs_eq);
    let rhs = parse_formula_pair(rhs_eq);

    ConjunctiveFormula::new(lhs, rhs)
}

/// Parses a [`Pairs<Rule>`] sequence into an instance of [`DisjunctiveFormula`]
fn parse_disjunction<'a>(eq: &mut Pairs<'a, Rule>) -> DisjunctiveFormula<'a> {
    // for lhs and rhs, get the inner type within the formula rule
    let lhs_eq = eq.next().unwrap();
    let lhs_eq = lhs_eq.into_inner().next().unwrap();

    let rhs_eq = eq.next().unwrap();
    let rhs_eq = rhs_eq.into_inner().next().unwrap();

    let lhs = parse_formula_pair(lhs_eq);
    let rhs = parse_formula_pair(rhs_eq);

    DisjunctiveFormula::new(lhs, rhs)
}

/// Parses a [`Pairs<Rule>`] sequence into an instance of [`ExistentialFormula`]
fn parse_existential<'a>(eq: &mut Pairs<'a, Rule>) -> ExistentialFormula<'a> {
    let variable_pair = eq.next().unwrap();
    if variable_pair.as_rule() != Rule::variable {
        panic!("Expected a variable to be bound in 'exists' clause")
    }
    let bound_variable = variable_pair.as_str();

    // 'inner' is the wrapping `formula` rule, so we go into that to get the inner formula type
    let inner = eq.next().unwrap().into_inner().next().unwrap();
    let inner_formula = parse_formula_pair(inner);

    ExistentialFormula::new(bound_variable, inner_formula)
}

/// Parses a [`Pairs<Rule>`] sequence into an instance of [`UniversalFormula`]
fn parse_universal<'a>(eq: &mut Pairs<'a, Rule>) -> UniversalFormula<'a> {
    let variable_pair = eq.next().unwrap();
    if variable_pair.as_rule() != Rule::variable {
        panic!("Expected a variable to be bound in 'exists' clause")
    }
    let bound_variable = variable_pair.as_str();

    // 'inner' is the wrapping `formula` rule, so we go into that to get the inner formula type
    let inner = eq.next().unwrap().into_inner().next().unwrap();
    let inner_formula = parse_formula_pair(inner);

    UniversalFormula::new(bound_variable, inner_formula)
}

/// Parse a pest `Pair` into a [`Formula`] `Box` pointer with the appropriate
/// implementation of [`Formula`] by calling the corresponding function on the [`Pair<Rule>`]
fn parse_formula_pair<'a>(pair: Pair<'a, Rule>) -> Box<dyn Formula + 'a> {
    match pair.as_rule() {
        Rule::negation => Box::from(parse_negation(&mut pair.into_inner())),
        Rule::simple_equation => Box::from(parse_atomic_equation(&mut pair.into_inner())),
        Rule::conjunction => Box::from(parse_conjunction(&mut pair.into_inner())),
        Rule::disjunction => Box::from(parse_disjunction(&mut pair.into_inner())),
        Rule::existential => Box::from(parse_existential(&mut pair.into_inner())),
        Rule::universal => Box::from(parse_universal(&mut pair.into_inner())),

        r => {
            panic!("Expected a formula type, round rule type {:?}", r);
        }
    }
}
