use crate::formula::{EquationContent, Formula, Quantifier};
use pest::iterators::{Pair, Pairs};
use pest::Parser;

/// The parser generated by [`pest`], implemented by the macro, using the grammar defined in
/// the file `formula.pest`
#[derive(pest_derive::Parser)]
#[grammar = "formula.pest"]
struct FormulaParser;

/// Tests that the generated parser [`FormulaParser`] doesn't fail on basic correct formulas
#[test]
fn test_parser() {
    let test_cases = [
        r#"x = "a" yqqq z"#,
        r#"¬x = "a" yqqq z"#,
        r#"(x=y"abc" && ¬y="m")"#,
    ];
    for case in test_cases {
        let rules = FormulaParser::parse(Rule::formula, case)
            .expect("should parse")
            .next()
            .unwrap();
        println!("Success {}", case);
        println!("{:#?}", rules);
    }
}

/// Creates a [`Formula`] object-based structural representation of the given formula string
pub fn parse_formula_str(eq: &'_ str) -> Option<Formula<'_>> {
    let res = FormulaParser::parse(Rule::formula, eq);
    if let Ok(mut formula) = res {
        let formula = formula.next().unwrap();
        let formula = formula.into_inner().next().unwrap();
        let formula = parse_formula_pair(formula);
        Some(formula)
    } else {
        let error = res.unwrap_err();
        eprintln!("Syntax error in formula: {}", error);
        None
    }
}

/// Tests that the function [`parse_formula_str`] doesn't fail on some simple correct formulas
#[cfg(test)]
#[test]
fn test_formula_parse() {
    let test_cases = [
        r#"x = "a" yqqq z"#,
        r#"¬q = "a""#,
        r#"¬x = "a" yqqq z"#,
        r#"(x=y"abc" && ¬y="")"#,
        r#"exists x ($U=x x)"#,
        r#"¬(x="aa"||x="bb")"#,
    ];
    for case in test_cases {
        let eq = parse_formula_str(case);
        match eq {
            None => {
                panic!("Parse error on formula\n{:?}", eq)
            }
            Some(val) => {
                println!("Success {:?}\n---------------", val);
            }
        }
    }
}

/// Parses a [`Pairs<Rule>`] sequence into a [`Formula::Equation`]
fn parse_equation<'a>(eq: &mut Pairs<'a, Rule>) -> Formula<'a> {
    let lhs = eq.next().unwrap().as_str();
    let rhs = eq
        .map(|x| match x.as_rule() {
            Rule::constant => {
                let str = x.as_str();
                // remove " at start and end
                EquationContent::Constant(str[1..str.len() - 1].into())
            }
            Rule::variable => EquationContent::Variable(x.as_str()),
            _ => panic!("Unreachable state"),
        })
        .collect();

    Formula::Equation { lhs, rhs }
}

/// Parses a [`Pairs<Rule>`] sequence into a [`Formula::Negation`]
fn parse_negation<'a>(eq: &mut Pairs<'a, Rule>) -> Formula<'a> {
    let inner_pair = eq.next().unwrap();
    let inner_formula = parse_formula_pair(inner_pair);
    Formula::Negation {
        inner: Box::new(inner_formula),
    }
}

/// Parses a [`Pairs<Rule>`] sequence into a [`Formula::Conjunction`]
fn parse_conjunction<'a>(eq: &mut Pairs<'a, Rule>) -> Formula<'a> {
    let mut fragments = Vec::new();
    loop {
        let fragment = eq.next();
        if let Some(fragment) = fragment {
            fragments.push(parse_formula_pair(fragment));
        } else {
            break;
        }
    }
    Formula::Conjunction { fragments }
}

/// Parses a [`Pairs<Rule>`] sequence into a [`Formula::Disjunction`]
fn parse_disjunction<'a>(eq: &mut Pairs<'a, Rule>) -> Formula<'a> {
    let mut fragments = Vec::new();
    loop {
        let fragment = eq.next();
        if let Some(fragment) = fragment {
            fragments.push(parse_formula_pair(fragment));
        } else {
            break;
        }
    }
    Formula::Disjunction { fragments }
}

/// Parses a [`Pairs<Rule>`] sequence into a [`Formula::Quantifier`]
fn parse_quantifier<'a>(eq: &mut Pairs<'a, Rule>, quantifier: Quantifier) -> Formula<'a> {
    let variable_pair = eq.next().unwrap();
    if variable_pair.as_rule() != Rule::variable {
        panic!("Expected a variable to be bound in 'exists' clause")
    }
    let bound_variable = variable_pair.as_str();

    // 'inner' is the wrapping `formula` rule, so we go into that to get the inner formula type
    let inner = eq.next().unwrap();
    let inner_formula = parse_formula_pair(inner);

    Formula::Quantifier {
        inner: Box::new(inner_formula),
        var: bound_variable,
        quantifier,
    }
}

/// Parse a pest `Pair` into a [`Formula`] `Box` pointer with the appropriate
/// implementation of [`Formula`] by calling the corresponding function on the [`Pair<Rule>`]
fn parse_formula_pair(pair: Pair<Rule>) -> Formula {
    match pair.as_rule() {
        Rule::negation => parse_negation(&mut pair.into_inner()),
        Rule::simple_equation => parse_equation(&mut pair.into_inner()),
        Rule::conjunction => parse_conjunction(&mut pair.into_inner()),
        Rule::disjunction => parse_disjunction(&mut pair.into_inner()),
        Rule::existential => parse_quantifier(&mut pair.into_inner(), Quantifier::Existential),
        Rule::universal => parse_quantifier(&mut pair.into_inner(), Quantifier::Universal),

        r => {
            panic!("Expected a formula type, found rule type {:?}", r);
        }
    }
}
