formula = { simple_equation | negation | conjunction | disjunction | existential | universal }

simple_equation = {variable ~ "=" ~ (constant | variable)+}
negation = {"¬" ~ formula}
conjunction = {"(" ~ formula ~ ("&&"|"∧") ~ formula ~ ")"}
disjunction = {"(" ~ formula ~ ("||"|"∨") ~ formula ~ ")"}
existential = {("exists" | "∃") ~ variable ~ "(" ~ formula ~ ")"}
universal = {("forall" | "∀") ~ variable ~ "(" ~ formula ~ ")"}

constant = {"\"" ~ ASCII_ALPHANUMERIC* ~ "\""}
variable = @{ASCII_ALPHA ~ (ASCII_ALPHANUMERIC)*} // atomic rule - no whitespace at separator

WHITESPACE = _{ " " } // Special rule name