word_equation = { atomic | neg_atomic | conjunctive_equation | disjunctive_equation | existential_equation | universal_equation }

atomic = {variable ~ "=" ~ (constant | variable)+}
neg_atomic = {"¬" ~ word_equation}
conjunctive_equation = {"(" ~ word_equation ~ ("&&"|"∧") ~ word_equation ~ ")"}
disjunctive_equation = {"(" ~ word_equation ~ ("||"|"∨") ~ word_equation ~ ")"}
existential_equation = {("exists" | "∃") ~ variable ~ "(" ~ word_equation ~ ")"}
universal_equation = {("forall" | "∀") ~ variable ~ "(" ~ word_equation ~ ")"}

constant = {"\"" ~ ASCII_ALPHANUMERIC* ~ "\""}
variable = @{ASCII_ALPHA ~ (ASCII_ALPHANUMERIC)*} // atomic rule - no whitespace at separator

WHITESPACE = _{ " " } // Special rule name